name: Deploy API (Express)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./api

      # Opcional: rodar testes
      # - name: Run tests
      #   run: npm test
      #   working-directory: ./api

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_API }}
          working-directory: ./api
          # Define o ambiente conforme a branch
          vercel-args: >-
            --prod=${{ github.ref == 'refs/heads/main' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}